### ISSUE TITLE
Can't instantiate USBDevice when the device doesn't provide the language ids descriptor

### ISSUE THREAD

**Issue by Konamiman** [madwizard-thomas/winusbnet#38]
The CH372 processor (and the compatible ones CH375 and CH376, when configured in device mode) has an "internal firmware mode" in which the chip itself takes care of all the control transfers on endpoint 0. In this mode the processor doesn't provide any string descriptor at all, not even the language IDs descriptor: a request for this descriptor will always fail.

This makes it impossible to use WinUSBNet to access such a device. That's because the `USBDevice` constructor calls its `GetDeviceDescriptor` method, which will in turn call `wuDevice.GetSupportedLanguageIDs()`; this is going to throw, and thus `GetDeviceDescriptor` throws and the entire instantiation fails.

The following alternative implementation of `USBDevice.GetDeviceDescriptor` fixes the problem. If any string descriptor related operation fails the device object is still created without any string information whatsoever (it could be improved by wrapping a `try` around each string descriptor request, up to you):

```c#
private static USBDeviceDescriptor GetDeviceDescriptor(string devicePath)
{
    using (API.WinUSBDevice wuDevice = new API.WinUSBDevice())
    {
        API.USB_DEVICE_DESCRIPTOR deviceDesc;

        try {
            wuDevice.OpenDevice(devicePath);
            deviceDesc = wuDevice.GetDeviceDescriptor();
        }
        catch (API.APIException e) {
            throw new USBException("Failed to retrieve device descriptor.", e);
        }

        try {
            // Get first supported language ID
            ushort[] langIDs = wuDevice.GetSupportedLanguageIDs();
            ushort langID = 0;
            if (langIDs.Length > 0)
                langID = langIDs[0];

            string manufacturer = null, product = null, serialNumber = null;
            byte idx = 0;
            idx = deviceDesc.iManufacturer;
            if (idx > 0)
                manufacturer = wuDevice.GetStringDescriptor(idx, langID);

            idx = deviceDesc.iProduct;
            if (idx > 0)
                product = wuDevice.GetStringDescriptor(idx, langID);

            idx = deviceDesc.iSerialNumber;
            if (idx > 0)
                serialNumber = wuDevice.GetStringDescriptor(idx, langID);

            return new USBDeviceDescriptor(devicePath, deviceDesc, manufacturer, product, serialNumber);
        }
        catch (API.APIException) {
            return new USBDeviceDescriptor(devicePath, deviceDesc, null, null, null);
        }
    }
}
```

**Comment by misaya** [comment]
MadWizard.WinUSBNet.USBException
  HResult=0x80131500
  Message=Failed to retrieve device descriptor.
  Source=WinUSBNet
  StackTrace:
   at MadWizard.WinUSBNet.USBDevice.GetDeviceDescriptor(String devicePath)
   at MadWizard.WinUSBNet.USBDevice..ctor(String devicePathName)
   at MadWizard.WinUSBNet.USBDevice..ctor(USBDeviceInfo deviceInfo)
   at WinUsbPrintTest.FrmMain.BtnCon_Click(Object sender, EventArgs e) in F:\WinUsbPrintTest\FrmMain.cs:line 33
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

内部异常 1:
APIException: Failed to initialize WinUSB handle. Device might not be connected.

内部异常 2:
Win32Exception: 内存资源不足，无法处理此命令。

**Comment by madwizard-thomas** [comment]
Hi, thanks for your report. Is there a specific error code that is thrown in this case? It would be good to work around the issue but I'm a bit hesitant to blankly ignore all API errors.
