### ISSUE TITLE
Failed to retrieve device descriptor.

### ISSUE THREAD

**Issue by misaya** [madwizard-thomas/winusbnet#39]
MadWizard.WinUSBNet.USBException
HResult=0x80131500
Message=Failed to retrieve device descriptor.
Source=WinUSBNet
StackTrace:
at MadWizard.WinUSBNet.USBDevice.GetDeviceDescriptor(String devicePath)
at MadWizard.WinUSBNet.USBDevice..ctor(String devicePathName)
at MadWizard.WinUSBNet.USBDevice..ctor(USBDeviceInfo deviceInfo)
at WinUsbPrintTest.FrmMain.BtnCon_Click(Object sender, EventArgs e) in F:\WinUsbPrintTest\FrmMain.cs:line 33
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

内部异常 1:
APIException: Failed to initialize WinUSB handle. Device might not be connected.

内部异常 2:
Win32Exception: 内存资源不足，无法处理此命令。

**Comment by madwizard-thomas** [comment]
Please write an actual bug report with a minimal example if there is a bug with WinUSBNet.
